/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IGU;
import com.mycompany.IGU.*;
        
/**
 *
 * @author User
 */
public class Consultas extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Consultas() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Sistema de cuentas por pagar");

        

        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MAS = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Consulta1 = new javax.swing.JButton();
        Consulta2 = new javax.swing.JButton();
        Consulta3 = new javax.swing.JButton();
        Consulta4 = new javax.swing.JButton();
        Consulta5 = new javax.swing.JButton();
        Consulta6 = new javax.swing.JButton();
        Consulta7 = new javax.swing.JButton();
        Consulta8 = new javax.swing.JButton();
        Consulta9 = new javax.swing.JButton();
        Consulta10 = new javax.swing.JButton();
        Consulta11 = new javax.swing.JButton();
        Consulta12 = new javax.swing.JButton();
        Consulta13 = new javax.swing.JButton();
        Consulta14 = new javax.swing.JButton();
        jDateChooserConsulta1 = new com.toedter.calendar.JDateChooser();
        jTextFieldConsulta14 = new javax.swing.JTextField();
        jTextFieldConsulta13 = new javax.swing.JTextField();
        jTextFieldConsulta4 = new javax.swing.JTextField();
        jTextFieldConsulta2 = new javax.swing.JTextField();
        jTextFieldConsulta3 = new javax.swing.JTextField();
        jTextFieldConsulta6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(java.awt.SystemColor.activeCaption);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consulta Multitabla");

        MAS.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        MAS.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        MAS.setText("<-");
        MAS.setToolTipText("");
        MAS.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.inactiveCaption, 4));
        MAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MASActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 385, Short.MAX_VALUE)
                .addComponent(MAS)
                .addGap(56, 56, 56))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(MAS, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 80));

        jPanel4.setBackground(java.awt.SystemColor.activeCaption);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Funciones");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(709, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 920, 80));

        jPanel5.setBackground(java.awt.SystemColor.activeCaption);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Procedimiento");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 920, 80));

        jPanel6.setBackground(java.awt.SystemColor.activeCaption);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Subconsulta");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(665, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 920, -1));

        Consulta1.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        Consulta1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Consulta1.setText("Consulta 1");
        Consulta1.setToolTipText("");
        Consulta1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.inactiveCaption, 4));
        Consulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consulta1ActionPerformed(evt);
            }
        });
        jPanel3.add(Consulta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 170, 30));

        Consulta2.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        Consulta2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Consulta2.setText("Consulta 2");
        Consulta2.setToolTipText("");
        Consulta2.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.inactiveCaption, 4));
        Consulta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consulta2ActionPerformed(evt);
            }
        });
        jPanel3.add(Consulta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 170, 30));

        Consulta3.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        Consulta3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Consulta3.setText("Consulta 3");
        Consulta3.setToolTipText("");
        Consulta3.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.inactiveCaption, 4));
        Consulta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consulta3ActionPerformed(evt);
            }
        });
        jPanel3.add(Consulta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 170, 30));

        Consulta4.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        Consulta4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Consulta4.setText("Consulta 4");
        Consulta4.setToolTipText("");
        Consulta4.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.inactiveCaption, 4));
        Consulta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consulta4ActionPerformed(evt);
            }
        });
        jPanel3.add(Consulta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 170, 30));

        Consulta5.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        Consulta5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Consulta5.setText("Consulta 5");
        Consulta5.setToolTipText("");
        Consulta5.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.inactiveCaption, 4));
        Consulta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consulta5ActionPerformed(evt);
            }
        });
        jPanel3.add(Consulta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 170, 30));

        Consulta6.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        Consulta6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Consulta6.setText("Consulta 6");
        Consulta6.setToolTipText("");
        Consulta6.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.inactiveCaption, 4));
        Consulta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consulta6ActionPerformed(evt);
            }
        });
        jPanel3.add(Consulta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 170, 30));

        Consulta7.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        Consulta7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Consulta7.setText("Consulta 7");
        Consulta7.setToolTipText("");
        Consulta7.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.inactiveCaption, 4));
        Consulta7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consulta7ActionPerformed(evt);
            }
        });
        jPanel3.add(Consulta7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 170, 30));

        Consulta8.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        Consulta8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Consulta8.setText("Consulta 8");
        Consulta8.setToolTipText("");
        Consulta8.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.inactiveCaption, 4));
        Consulta8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consulta8ActionPerformed(evt);
            }
        });
        jPanel3.add(Consulta8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 170, 30));

        Consulta9.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        Consulta9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Consulta9.setText("Consulta 9");
        Consulta9.setToolTipText("");
        Consulta9.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.inactiveCaption, 4));
        Consulta9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consulta9ActionPerformed(evt);
            }
        });
        jPanel3.add(Consulta9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, 170, 30));

        Consulta10.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        Consulta10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Consulta10.setText("Consulta 10");
        Consulta10.setToolTipText("");
        Consulta10.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.inactiveCaption, 4));
        Consulta10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consulta10ActionPerformed(evt);
            }
        });
        jPanel3.add(Consulta10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 670, 170, 30));

        Consulta11.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        Consulta11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Consulta11.setText("Consulta 11");
        Consulta11.setToolTipText("");
        Consulta11.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.inactiveCaption, 4));
        Consulta11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consulta11ActionPerformed(evt);
            }
        });
        jPanel3.add(Consulta11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 670, 170, 30));

        Consulta12.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        Consulta12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Consulta12.setText("Consulta 12");
        Consulta12.setToolTipText("");
        Consulta12.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.inactiveCaption, 4));
        Consulta12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consulta12ActionPerformed(evt);
            }
        });
        jPanel3.add(Consulta12, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 670, 170, 30));

        Consulta13.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        Consulta13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Consulta13.setText("Consulta 13");
        Consulta13.setToolTipText("");
        Consulta13.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.inactiveCaption, 4));
        Consulta13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consulta13ActionPerformed(evt);
            }
        });
        jPanel3.add(Consulta13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 170, 30));

        Consulta14.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        Consulta14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Consulta14.setText("Consulta 14");
        Consulta14.setToolTipText("");
        Consulta14.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.inactiveCaption, 4));
        Consulta14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consulta14ActionPerformed(evt);
            }
        });
        jPanel3.add(Consulta14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 170, 30));
        jPanel3.add(jDateChooserConsulta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 170, -1));
        jPanel3.add(jTextFieldConsulta14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 170, -1));
        jPanel3.add(jTextFieldConsulta13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 170, -1));
        jPanel3.add(jTextFieldConsulta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 170, -1));
        jPanel3.add(jTextFieldConsulta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 170, -1));
        jPanel3.add(jTextFieldConsulta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 170, -1));
        jPanel3.add(jTextFieldConsulta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 170, -1));

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 923, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MASActionPerformed
        Principal F1 = new Principal ();
        F1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MASActionPerformed

    private void Consulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consulta1ActionPerformed
           CConsultas C1= new CConsultas();
           C1.Consulta1(jDateChooserConsulta1);
    }//GEN-LAST:event_Consulta1ActionPerformed

    private void Consulta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consulta2ActionPerformed
                   CConsultas C1= new CConsultas();
           C1.Consulta2(jTextFieldConsulta2);
    }//GEN-LAST:event_Consulta2ActionPerformed

    private void Consulta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consulta3ActionPerformed
                   CConsultas C1= new CConsultas();
           C1.Consulta3(jTextFieldConsulta3);
    }//GEN-LAST:event_Consulta3ActionPerformed

    private void Consulta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consulta4ActionPerformed
                   CConsultas C1= new CConsultas();
           C1.Consulta4(jTextFieldConsulta4);
    }//GEN-LAST:event_Consulta4ActionPerformed

    private void Consulta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consulta5ActionPerformed
                   CConsultas C1= new CConsultas();
           C1.Consulta5();
    }//GEN-LAST:event_Consulta5ActionPerformed

    private void Consulta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consulta6ActionPerformed
                   CConsultas C1= new CConsultas();
           C1.Consulta6(jTextFieldConsulta6.getText());
    }//GEN-LAST:event_Consulta6ActionPerformed

    private void Consulta7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consulta7ActionPerformed
                   CConsultas C1= new CConsultas();
           C1.Consulta7();
    }//GEN-LAST:event_Consulta7ActionPerformed

    private void Consulta8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consulta8ActionPerformed
                  CConsultas C1= new CConsultas();
           C1.Consulta8();
    }//GEN-LAST:event_Consulta8ActionPerformed

    private void Consulta9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consulta9ActionPerformed
                   CConsultas C1= new CConsultas();
           C1.Consulta9();
    }//GEN-LAST:event_Consulta9ActionPerformed

    private void Consulta10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consulta10ActionPerformed
                   CConsultas C1= new CConsultas();
           C1.Consulta10();
    }//GEN-LAST:event_Consulta10ActionPerformed

    private void Consulta11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consulta11ActionPerformed
                   CConsultas C1= new CConsultas();
           C1.Consulta11();
    }//GEN-LAST:event_Consulta11ActionPerformed

    private void Consulta12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consulta12ActionPerformed
                   CConsultas C1= new CConsultas();
           C1.Consulta12();
    }//GEN-LAST:event_Consulta12ActionPerformed

    private void Consulta13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consulta13ActionPerformed
                   CConsultas C1= new CConsultas();
           C1.Consulta13(jTextFieldConsulta13);
    }//GEN-LAST:event_Consulta13ActionPerformed

    private void Consulta14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consulta14ActionPerformed
                   CConsultas C1= new CConsultas();
           C1.Consulta14(jTextFieldConsulta14);
    }//GEN-LAST:event_Consulta14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Consulta1;
    private javax.swing.JButton Consulta10;
    private javax.swing.JButton Consulta11;
    private javax.swing.JButton Consulta12;
    private javax.swing.JButton Consulta13;
    private javax.swing.JButton Consulta14;
    private javax.swing.JButton Consulta2;
    private javax.swing.JButton Consulta3;
    private javax.swing.JButton Consulta4;
    private javax.swing.JButton Consulta5;
    private javax.swing.JButton Consulta6;
    private javax.swing.JButton Consulta7;
    private javax.swing.JButton Consulta8;
    private javax.swing.JButton Consulta9;
    private javax.swing.JButton MAS;
    private com.toedter.calendar.JDateChooser jDateChooserConsulta1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldConsulta13;
    private javax.swing.JTextField jTextFieldConsulta14;
    private javax.swing.JTextField jTextFieldConsulta2;
    private javax.swing.JTextField jTextFieldConsulta3;
    private javax.swing.JTextField jTextFieldConsulta4;
    private javax.swing.JTextField jTextFieldConsulta6;
    // End of variables declaration//GEN-END:variables
}
