/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IGU;
import com.mycompany.IGU.*;
import javax.swing.ButtonGroup;
        
/**
 *
 * @author User
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Sistema de cuentas por pagar");
        CFactura ObjetoFactura = new CFactura ();
        ObjetoFactura.mostrarFactu(jTable1);
        ButtonGroup group = new ButtonGroup();      
        group.add(jRadioButton1);
        group.add(jRadioButton2);
        group.add(jRadioButton3);       
        group.add(jRadioButton4);

        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        MAS = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        PRODUCTOS = new javax.swing.JButton();
        Pagar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        RegistrarProveedor1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        CrearFactura1 = new javax.swing.JButton();
        MedioDePago = new javax.swing.JButton();
        CondPago1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MAS.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        MAS.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        MAS.setText("+");
        MAS.setToolTipText("");
        MAS.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.inactiveCaption, 4));
        MAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MASActionPerformed(evt);
            }
        });
        jPanel3.add(MAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 450, 50, 60));

        jButton2.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("GUIA ALMACEN");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.inactiveCaption, 4));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 170, 30));

        PRODUCTOS.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        PRODUCTOS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PRODUCTOS.setText("PRODUCTOS");
        PRODUCTOS.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.inactiveCaption, 4));
        PRODUCTOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRODUCTOSActionPerformed(evt);
            }
        });
        jPanel3.add(PRODUCTOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 170, 30));

        Pagar.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        Pagar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Pagar.setText("CAJA BANCO");
        Pagar.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.inactiveCaption, 4));
        Pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagarActionPerformed(evt);
            }
        });
        jPanel3.add(Pagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 170, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 600, 210));

        jButton7.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setText("EMPLEADO");
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.inactiveCaption, 4));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 170, 30));

        RegistrarProveedor1.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        RegistrarProveedor1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RegistrarProveedor1.setText("PROVEEDOR");
        RegistrarProveedor1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.inactiveCaption, 4));
        RegistrarProveedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarProveedor1ActionPerformed(evt);
            }
        });
        jPanel3.add(RegistrarProveedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 170, 30));

        jPanel2.setBackground(java.awt.SystemColor.activeCaption);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cuentas por pagar");

        jPanel1.setBackground(java.awt.SystemColor.inactiveCaption);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        jLabel2.setText("Consulta de Facturas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 6, -1, -1));

        jRadioButton1.setBackground(java.awt.SystemColor.inactiveCaption);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jRadioButton1.setText("30 dias");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 31, -1, -1));

        jRadioButton2.setBackground(java.awt.SystemColor.inactiveCaption);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jRadioButton2.setText("60 dias");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 31, -1, -1));

        jRadioButton3.setBackground(java.awt.SystemColor.inactiveCaption);
        jRadioButton3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jRadioButton3.setText("All");
        jRadioButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton3MouseClicked(evt);
            }
        });
        jPanel1.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jRadioButton4.setBackground(java.awt.SystemColor.inactiveCaption);
        jRadioButton4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jRadioButton4.setText("90 dias");
        jRadioButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton4MouseClicked(evt);
            }
        });
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 31, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 120));

        CrearFactura1.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        CrearFactura1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CrearFactura1.setText("FACTURA");
        CrearFactura1.setToolTipText("");
        CrearFactura1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.inactiveCaption, 4));
        CrearFactura1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearFactura1ActionPerformed(evt);
            }
        });
        jPanel3.add(CrearFactura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 170, 30));

        MedioDePago.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        MedioDePago.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MedioDePago.setText("MEDIO DE PAGO");
        MedioDePago.setToolTipText("");
        MedioDePago.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.inactiveCaption, 4));
        MedioDePago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MedioDePagoMouseClicked(evt);
            }
        });
        MedioDePago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedioDePagoActionPerformed(evt);
            }
        });
        jPanel3.add(MedioDePago, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 170, 30));

        CondPago1.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        CondPago1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CondPago1.setText("CONDICION DE PAGO");
        CondPago1.setToolTipText("");
        CondPago1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.inactiveCaption, 4));
        CondPago1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CondPago1ActionPerformed(evt);
            }
        });
        jPanel3.add(CondPago1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 170, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 907, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void PRODUCTOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRODUCTOSActionPerformed
            VerProductos f1 = new VerProductos();
            f1.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_PRODUCTOSActionPerformed

    private void PagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagarActionPerformed
        CajaBanco pagar = new CajaBanco();
        pagar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_PagarActionPerformed

    private void MASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MASActionPerformed
                Consultas crearFactura = new Consultas();
                crearFactura.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_MASActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CrearGuiaAlmacen crearGuiaAlmacen = new CrearGuiaAlmacen();
        crearGuiaAlmacen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void RegistrarProveedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarProveedor1ActionPerformed
        RegistrarProveedor registrarProveedor = new RegistrarProveedor();
        registrarProveedor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegistrarProveedor1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        RegistrarEmpleado registrarEmpleado = new RegistrarEmpleado();
        registrarEmpleado.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void CrearFactura1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearFactura1ActionPerformed
            CrearFactura    C1 = new CrearFactura();
            C1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CrearFactura1ActionPerformed

    private void MedioDePagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedioDePagoActionPerformed


    }//GEN-LAST:event_MedioDePagoActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void MedioDePagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MedioDePagoMouseClicked
        CrearMedioDePago C1 = new CrearMedioDePago();
        C1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MedioDePagoMouseClicked

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
    CFactura O1 = new CFactura();
    O1.mostrarFactu30Dias(jTable1);
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked
    CFactura O1 = new CFactura();
    O1.mostrarFactu60Dias(jTable1);
    }//GEN-LAST:event_jRadioButton2MouseClicked

    private void jRadioButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton4MouseClicked
    CFactura O1 = new CFactura();
    O1.mostrarFactu90Dias(jTable1);
    }//GEN-LAST:event_jRadioButton4MouseClicked

    private void jRadioButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton3MouseClicked
        CFactura O1 = new CFactura();
    O1.mostrarFactu(jTable1);
    }//GEN-LAST:event_jRadioButton3MouseClicked

    private void CondPago1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CondPago1ActionPerformed
            CrearCondicionDePago c1 = new CrearCondicionDePago();
            c1.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_CondPago1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CondPago1;
    private javax.swing.JButton CrearFactura1;
    private javax.swing.JButton MAS;
    private javax.swing.JButton MedioDePago;
    private javax.swing.JButton PRODUCTOS;
    private javax.swing.JButton Pagar;
    private javax.swing.JButton RegistrarProveedor1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
